config/routes.rb
Rails.application.routes.draw do
  resources :checkouts
  root 'welcome#index'
  get '/logout', to: 'sessions#destroy'
  get '/listings/analytics', to: 'listings#analytics'
  resources :users
  resources :sessions
  resources :reviews
  resources :rentals
  resources :listings
  resources :tools
  post '/checkouts/add', to: 'checkouts#add'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tool.rb
class Tool < ApplicationRecord
  has_many :reviews
  has_one :listing
  belongs_to :lender, :class_name => "User"
  validates :name, presence: true
  validates :safety_level, presence: true
  validates :condition, {presence: true, length: {in: 1..250}}


  def self.with_listings
    self.select do |tool|
      tool.has_listing?
    end
  end

  def without_listings
    self.select do |tool|
      !(tool.has_listing?)
    end
  end

  def has_listing?
    self.listing
  end

  def proper_tool_name(tool_name)
    tool_name.downcase.capitalize
  end


  def average_review
    if !self.reviews.empty?
      ratings_array = self.reviews.map do |review|
        review.rating
      end
      ((ratings_array.inject(:+)).to_f/(ratings_array.size).to_f).round(1)
    else
      "This has no reviews yet"
    end
  end

  def self.highest_rated
    sql = <<-SQL
    SELECT  AVG(reviews.rating) AS tool_rating_average, tools.name
    FROM reviews
    JOIN listings ON reviews.tool_id = listings.tool_id
    JOIN tools ON tools.id = listings.tool_id
    WHERE reviews.rating >= 4
    GROUP BY tools.name
    SQL
    tools = self.find_by_sql(sql)
    tools.map {|tool| tool.name}
  end

  def available?
    self.availability == "Available"
  end


end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController


    def index

      pie = <<-SQL
        select listings.tool_id, count(*) as count
        from listings inner join tools on listings.tool_id = tools.id
        group by listings.tool_id
        SQL
        names = Listing.find_by_sql(pie)
      @tool_name_pie = names.map do |listing|
        [Tool.find(listing.tool_id).name, listing.count]
      end

    sql = <<-SQL
      select tools.lender_id, count(*) as count
      from tools inner join users on tools.lender_id = users.id
      group by tools.lender_id
    SQL
    tools = Tool.find_by_sql(sql)

    @chart_info = tools.map do |tool|
      [User.find(tool.lender_id).name, tool.count]

    end

    @reviews = Review.all
    chart_info = Review.find_by_sql("SELECT rating, count(*) as count FROM reviews GROUP BY rating" )

@user = User.find(session[:user_id])

  #review chart data
    sql = <<-SQL
      select reviews.rating, count(*) as count
      from reviews
      group by reviews.rating
      SQL
      info = Review.find_by_sql(sql)
    @review_chart = info.map do |review|
      [review.rating, review.count]
    end
  end

  def new
    @tool = Tool.new
    @user = User.find(session[:user_id])
  end

  def create
    @user = User.find(session[:user_id])
    @tool = Tool.new(name: params[:tool][:name], safety_level: params[:tool][:safety_level], portability: params[:tool][:portability], condition: params[:tool][:condition], lender_id: session[:user_id])
    if @tool.save
      @tool.name = @tool.proper_tool_name(@tool.name)
      @tool.save
      redirect_to tool_path(@tool)
    else
      render new_tool_path
    end
  end

  def show
    @tool = Tool.find(params[:id])
    @listing = @tool.listing
    @owner = User.find(session[:user_id])
    #
    # @tool.reviews << @review

  end

  def edit
    @tool = Tool.find(params[:id])
  end

  def update
    tool = Tool.find(params[:id])
    tool.update(name: params[:tool][:name], safety_level: params[:tool][:safety_level], portability: params[:tool][:portability], condition: params[:tool][:condition], availability: params[:tool][:availability])
    if tool.valid?
      tool.name = tool.proper_tool_name(tool.name)
      tool.save
      @tool = tool
      redirect_to tool_path(@tool)
    else
      render :edit
    end
  end

  def destroy
    tool = Tool.find(params[:id])
    @user = User.find(session[:user_id])
    tool.delete
    redirect_to user_path(@user)
  end

  private
  def tool_params(*args)
    params.require(:tool).permit(*args)
  end
end

app/views/tools/edit.html.erb
<h1>Edit Your Tool</h1>

<%= form_for @tool do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :safety_level %>
  <%= f.select :safety_level, [['safe'], ['not-so-safe'], ['be careful'], ['dangerous'], ['life-threatening']] %>
  <%= f.label :portability %>
  <%= f.text_field :portability %>
  <%= f.label :condition %>
  <%= f.text_field :condition %>
  <%= f.label :availability %>
  <%= f.select :availability, [["Available"],["Not Available"]] %>
  <%= f.submit %>
<% end %>

app/views/tools/index.html.erb
<%=javascript_include_tag "//google.com/jsapi", "chartkick" %>

<h1>Number of tools by user names</h1>
<%= column_chart(@chart_info) %>

<h1>Number and percentage of tools with listings by name</h1>
<%= pie_chart(@tool_name_pie) %>

<h1>Average review rating by tool</h1>
We have <%= @reviews.number_of_reviews %> reviews and counting!
<br>
<br>
Plus <%= @reviews.number_of_solid_reviews %> of those reviews were classified as thorough and helpful by our users!
<br>
<br>
See below for rating info! Most of our tools have ratings above 3!
<!-- <%= column_chart Review.group(:rating).count,{library: {hAxis: {title: "Tool Rating"}, vAxis: {title: "Count"}}, :title => "Ratings!", :colors => ["gray"], :id => "Ratings by Count"}  %> -->
<%= column_chart(@review_chart) %>


<%= button_to 'Return to User Page', user_path(@user), :method => :get%>

app/views/tools/new.html.erb
<div class="container">
<% if @tool.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@tool.errors.count, "error") %>
      prohibited this listing from being saved:
    </h2>

    <ul>
    <% @tool.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%=form_for @tool do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :portability %>
  <%= f.text_field :portability %>
  <br>
  <%= f.label :condition %>
  <%= f.text_field :condition %>
  <br>
  <%= f.select :safety_level, ['safe','not-so-safe','be careful','dangerous','life-threatening'] %>
  <br>
  <%=f.submit%>
<% end %>
</div><!--.container-->

app/views/tools/show.html.erb
<div class="container">
<h1>Tool Information</h1>

  <ul>
    <li>Name: <%= @tool.name %></li>
    <li>Safety Level: <%= @tool.safety_level %></li>
    <li>Portability: <%= @tool.portability %></li>
    <li>Condition: <%= @tool.condition %></li>
    <li>Availability: <%= @tool.availability %></li>

  </ul>

  Average Review: <%= @tool.average_review %><br>
  <br>
  <% if @tool.reviews.count > 0%>
  Reviews:<br>
    <% @tool.reviews.each do |review| %>
    Rating:<%= review.rating %><br>
    Content: <%= review.content%><br>
    Worth borrowing? <%= review.worth_borrowing? %><br>
    <% if @owner.id == review.borrower_id %>
    <%= link_to "Edit or delete", edit_review_path(review)%>
    <% end %>
    <br>
    <br>
    <% end %>
    <br>
    <% end%>

  <% if @tool.listing%>
  <%= button_to 'View Listing', listing_path(@listing), :method => :get %>
  <% else %>
  <%= button_to 'New Listing', new_listing_path, :method => :get  %>
  <% end %>
  <% if @owner.id == @tool.lender_id %>
  <%= button_to 'Edit Tool', edit_tool_path(@tool), :method => :get %>
  <%= button_to 'Delete Tool', tool_path(@tool), :method => :delete  %>
  <% end %>
</div><!--.container-->