config/routes.rb
Rails.application.routes.draw do
  resources :checkouts
  root 'welcome#index'
  get '/logout', to: 'sessions#destroy'
  get '/listings/analytics', to: 'listings#analytics'
  resources :users
  resources :sessions
  resources :reviews
  resources :rentals
  resources :listings
  resources :tools
  post '/checkouts/add', to: 'checkouts#add'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord

  belongs_to :tool
  validates :title, presence: true
  validates :notes, length: {in: 1..250}
  # belongs_to :lender, :class_name => "User", through: tool


  def find_lender
    self.tool.lender
    #test : given this tool, find a lender
  end

  def tool_name
    Tool.find(self.tool_id).name
  end

  # def self.by_zip_code(zip_code)
  #   sql = <<-SQL
  #     SELECT users.zip_code, tools.name FROM listings
  #     JOIN tools ON listings.tool_id = tools.id
  #     JOIN users ON tools.lender_id = users.id
  #     WHERE users.zip_code = #{zip_code}
  #   SQL
  #   self.find_by_sql(sql)
  # end

  def is_integer?
    self.to_i.to_s == self
  end

  def available_listing
    self.tool.availability == "Available"
  end

  def select_available_listings(list)
    list.select {|listing| listing.tool.availability == "Available" }
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  def index
    if params[:search]
      @listings = APIMaps.search(params[:search]).select {|listing| listing.tool.available? }
    else
      @listings = Listing.all#.select {|listing| listing.tool.available? }
    end
  end

    # if params[:zip_code]
    #   @zip_code_search = Listing.by_zip_code(params[:zip_code])
    # end

  def new
      @listing = Listing.new
      @user= User.find(session[:user_id])
      @tools = @user.tools
      @tools_without_listings = @user.your_tools_without_listings
  end

  def create
    @listing = Listing.new(notes: params[:listing][:notes], title: params[:listing][:title], tool_id: params[:listing][:tool_id])
    @user = User.find(session[:user_id])
    if @listing.save
      redirect_to user_path(@user)
    else
      render new_listing_path
    end
  end

  def show
    @listing = Listing.find(params[:id])
    @tool = Tool.find(@listing.tool_id)
    @owner = User.find(@tool.lender_id)
    @user = User.find(session[:user_id])


  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def update
    @user = User.find(session[:user_id])
    @listing = Listing.find(params[:id])
    @listing.update(notes: params[:listing][:notes], title: params[:listing][:title])
    if @listing.valid?
      @listing.save
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    listing = Listing.find(params[:id])
    @user = User.find(session[:user_id])
    listing.delete
    redirect_to user_path(@user)
  end



  private
  def listing_params(*args)
    params.require(:listing).permit(*args)
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/edit.html.erb
<h1>Edit Your Listing</h1>

<%= form_for @listing do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, :value => @listing.title %> <br />
  <%= f.label :notes %>
  <%= f.text_field :notes, :value => @listing.notes %> <br />
  <%= f.submit %>
<% end %>

app/views/listings/index.html.erb
<head>
  <link rel="stylesheet" href="/css/listing_index.css" />
</head>

<h1>All Listings</h1>

<h3>Search for a listing:</h3>

<%= form_tag listings_path, :method => :get do %>
  <%= label_tag "Search" %>
  <%= text_field_tag :search %>
  <%= submit_tag "Submit" %>
<% end %>
<br />
<table>
    <tr class="table-header-row">
      <th class="col-md-4">Listing Title</th>
      <th class="col-md-4">Tool</th>
      <th class="col-md-4">Notes</th>
    </tr>
<% @listings.each do |listing| %>
    <tr class="listing-row">
      <td><%= link_to listing.title, listing_path(listing) %></td>
      <td><%= listing.tool_name %></td>
      <td><%= listing.notes %></td>
    </tr>
<%end%>
</table>
<br />

<% if params[:search] != nil && params[:search].to_i != 0 %>
  <iframe
    width="600"
    height="450"
    frameborder="0" style="border:0"
    src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBYV-lwaMb8p0Hz04ILnsVSvHDZD2pZ7rc
      &q=<%=params[:search]%>" allowfullscreen>
  </iframe>
  <% end %>

<br />

app/views/listings/new.html.erb
<h3>Create a listing</h3>

<% if @listing.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@listing.errors.count, "error") %>
      prohibited this listing from being saved:
    </h2>

    <ul>
    <% @listing.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%=form_for @listing do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :notes %>
  <%= f.text_area :notes %>
  <br>
  What tool do you want to list?
  <br>
  <%= f.select :tool_id, @user.your_tools_without_listings.map {|tool| [tool.name, tool.id]} %>

  <%=f.submit%>
<% end %>

app/views/listings/show.html.erb
<h1><%= @listing.title %></h1>
<ul>
  <li>Tool: <%= @tool.name %></li>
  <li>Safety Level: <%= @tool.safety_level%></li>
  <li>Portability: <%= @tool.portability%></li>
  <li>Condition: <%= @tool.condition%></li>
  <li>Notes: <%= @listing.notes %></li>
  <li>Contact: <%= @owner.email%></li>
  <li>Availability: <%= @tool.availability%></li>

</ul>

Average Review: <%= @tool.average_review %><br>
<br>
<% if @tool.reviews.count > 0%>
Reviews:<br>
  <% @tool.reviews.each do |review| %>
  Rating:<%= review.rating %><br>
  Content: <%= review.content%><br>
  Worth borrowing? <%= review.worth_borrowing? %><br>

  <% if @user.id == review.borrower_id %>
  <%= link_to "Edit or delete", edit_review_path(review)%>
  <% end %>
  <br>
  <br>
  <% end %>
  <br>
  <% end %>

<% if @user.id != @tool.lender_id %>
  <%= button_to 'Review This Listing', new_review_path, :method => :get  %>

  <%= form_tag rentals_path do %>
  <%= hidden_field_tag 'listing_id', @listing.id %>
  <%= submit_tag 'Rent This Tool' %>
  <% end %>

<% end %>
<% if @user.id == @tool.lender_id %>
<%= button_to 'Edit Listing', edit_listing_path(@listing), :method => :get  %>
<%= button_to 'Delete Listing', listing_path(@listing), :method => :delete  %></p>
<%= button_to 'Return to Tool', tool_path(@tool), :method => :get %>
<% end %>