config/routes.rb
Rails.application.routes.draw do
  resources :checkouts
  root 'welcome#index'
  get '/logout', to: 'sessions#destroy'
  get '/listings/analytics', to: 'listings#analytics'
  resources :users
  resources :sessions
  resources :reviews
  resources :rentals
  resources :listings
  resources :tools
  post '/checkouts/add', to: 'checkouts#add'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :rentals, :foreign_key => 'borrower_id',as: :review_poly
  has_many :tools, :foreign_key => 'lender_id'
  has_many :listings, through: :tools, :foreign_key => 'lender_id'
  has_many :reviews, :foreign_key => 'borrower_id'

  validates :name, presence: true
  validates :email, uniqueness: true
  validates :location, presence: true
  validates :zip_code, presence: true
  validates :zip_code, numericality: true
  validates :zip_code, length: { is: 5 }

  def all_tools
    self.tools.map {|tool| tool}
  end

  def your_tools_without_listings
    self.tools.select do |tool|
      tool.listing == nil
    end
  end

  def all_reviews
    all_tools.map {|tool| tool.reviews}.flatten
  end

  def self.elite_users
    #users who have average review totals of 4 or higher

    #for each user, collect all reviews
    #Review.find_by_sql('SELECT tool_id, count(tool_id) FROM reviews GROUP BY tool_id')
    #average the rating for those reivews
    #if rating > 4 then user is elite
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  


  def index

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(name: params[:user][:name], email: params[:user][:email], location: params[:user][:location],password: params[:user][:password],password_confirmation: params[:user][:password_confirmation], zip_code: params[:user][:zip_code])
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show

    if session[:user_id] == params[:id].to_i
      @user = User.find(params[:id])

    else
      redirect_to user_path(session[:user_id])
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(name: params[:user][:name], email: params[:user][:email], location: params[:user][:location], zip_code: params[:user][:zip_code])
    if @user.valid?
      @user.save
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    session.destroy
    user = User.find(params[:id])
    user.delete
    redirect_to root_path
  end

  private
  def user_params(*args)
    params.require(:user).permit(*args)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Edit Your Information</h1>

<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :value => @user.name %> <br />
  <%= f.label :email %>
  <%= f.text_field :email, :value => @user.email %> <br />
  <%= f.label :location %>
  <%= f.text_field :location, :value => @user.location %> <br />
  <%= f.label :zip_code %>
  <%= f.text_field :zip_code, :value => @user.zip_code %> <br />
  <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<head>
  <link rel="stylesheet" href="/css/users_new.css" />
</head>

<div class="container">
    <h1>Sign up for T&uuml;l!</h1>

    <% if @user.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <h2>
          <%= pluralize(@user.errors.count, "error") %>
          prohibited this listing from being saved:
        </h2>

        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>


    <%= form_for @user do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <br>
        <%= f.label :address %>
        <%= f.text_field :location %>
        <br>
        <%= f.label :zip_code %>
        <%= f.text_field :zip_code %>
        <br>
        <%= f.label :email %>
        <%= f.text_field :email %>
        <br>
        <%= f.label :password %>
        <%= f.password_field :password %>
        <br>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
        <br>

        <%= f.submit "Sign Up"%>
      <% end %>
</div><!--.container-->

app/views/users/show.html.erb
<head>
  <link rel="stylesheet" href="/css/users_show.css" />
</head>

<div class="container">

  <div class="row">
    <h3>Your tools</h3>
     <%= button_to 'Add a Tool', new_tool_path, :method => :get, class: 'btn btn-primary' %>
      <ul>
      <% @user.tools.each do |tool| %>
        <li><%= link_to(tool.name, tool_path(tool)) %></li>
        <% end %>
      </ul>
  <hr />
  </div><!--.row-->
  <div class="row">
    <h3>Your listings:</h3>
    <ul>
      <% @user.tools.with_listings.map do |tool| %>
        <li><%= link_to(tool.listing.title, tool.listing(tool.listing)) %></li>
      <% end %>

      <%= form_tag listings_path, :method => :get do %>
        <%= label_tag "Search" %>
        <%= text_field_tag :search %>
        <%= submit_tag "Submit", class: 'btn btn-primary' %>
      <% end %>
      <br />
    <%= button_to 'Show All Listings', listings_path, :method => :get, class: 'btn btn-primary'   %>
    </ul>
    <hr />
  </div><!--.row-->

  <div class="row">
    <div class="col-md-6">
      <h3>Personal Information</h3>
      <ul>
        <li>Address: <%= @user.location %></li>
        <li>Zip Code: <%= @user.zip_code %></li>
        <li>Email: <%= @user.email %></li>
      </ul>
      <%= button_to 'Edit User', edit_user_path(@user), :method => :get, class: 'btn btn-warning' %>
      <%= button_to 'Delete Account', user_path(@user), :method => :delete, class: 'btn btn-danger' %>

    </div><!--.col-md-6-->
    <div class="col-md-6">
      <iframe
      width="300"
      height="225"
      frameborder="0" style="border:0"
      src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBYV-lwaMb8p0Hz04ILnsVSvHDZD2pZ7rc
        &q=<%=@user.zip_code%>" allowfullscreen>
    </iframe>
    </div><!--.col-md-6-->
  </div><!--.row-->

  <div class="row">
    <h3>Site Analytics</h3>
    <%= button_to 'Analytics', tools_path, :method => :get, class: 'btn btn-primary'   %>
  </div><!--.row-->


</div><!--.container-->